name = "OpenTesting.AI"
license = "Apache 2.0"
licenselink = "https://github.com/google/docsy/blob/main/LICENSE"
description = "xpto v"
homepage = ""
tags = ["documentation", "multilingual", "customizable", "responsive", "docs"]
features = []
min_version = "0.110.0"

[author]
  name = "The Docsy Authors"
  homepage = "https://docsy.dev"
